### ISSUE TITLE
Option to disable the "Nothing loading?" button

### ISSUE THREAD

**Issue by tambry** [craigmhughes/TidyTube#3]
It appearing everytime and then quickly disappearing is annoying. It'd be useful to not have it at all.

Besides, it seems to be always displayed on [the main page](https://www.youtube.com).

**Comment by craigmhughes** [comment]
Thanks for letting me know about this.

I included this as YouTube can force so much Recommended content that sometimes everything will hide as there is nothing from the user's subscriptions being loaded. So I displayed the button to let the user know that YouTube isn't broken, it just needs reloading.

I don't think I should remove it yet (unless I hear more about this) but I will definitely work on having it optional.

**Comment by craigmhughes** [comment]
Just created a popup that will now have the options to toggle what you need. Just press the TidyTube icon and it'll be there with the new update.
