### ISSUE TITLE
Extension no longer works due to type error

### ISSUE THREAD

**Issue by tambry** [craigmhughes/TidyTube#5]
Seems to happen on all videos for me.

```
Uncaught TypeError: Cannot read property 'style' of null
    at testURL (chrome-extension://eillffkhnelgaaladkpjeggognlimgbl/content.js:138)
    at HTMLBodyElement.<anonymous> (chrome-extension://eillffkhnelgaaladkpjeggognlimgbl/content.js:199)
```

[Code causing the error](https://github.com/craigmhughes/TidyTube/blob/185f001b9a0b98e99346be6a6ced298282675741/content.js#L138)

**Comment by craigmhughes** [comment]
Where were you when you encountered this error?

**Comment by tambry** [comment]
@craigmhughes It happens on any video for me. For example, even on [this Nyan cat video](https://www.youtube.com/watch?v=QH2-TGUlwu4).

**Comment by craigmhughes** [comment]
Weird, I'm trying every test I can think of to find a break but it doesn't happen for me. I can't believe I'm about to say this but what happened when you refreshed the page, still the same?

**Comment by tambry** [comment]
Refreshing the page still results in the same. It even happens in icognito mode after doing a cacheless refresh with CTRL+F5 and TidyTube is the only extension enabled.

But I noticed that when the "Nothing Loading" button is enabled, it results in a similar error (the previously mentioned error still occurs afterwards):
```
content.js:67 Uncaught TypeError: Cannot read property 'style' of null
    at ttSetup (content.js:67)
    at content.js:33
```

**Comment by craigmhughes** [comment]
Okay, I'm going to be adding some conditionals that will execute only when those elements can be read. I should've done this in the first place. Hopefully this will resolve your issues. Fingers crossed.

**Comment by tambry** [comment]
Worth noting that due to these errors, the "Related" section doesn't get removed and thus still shows up. Silencing the errors probably won't make it work.

[Here's the HTML](https://gist.githubusercontent.com/tambry/43be85462ba6ff90d2cd0c41e56a17b1/raw/31c08d5e877cf7a91006cd1e3143045fbab1f7df/example_video) that I receive for the Nyan cat video.

**Comment by craigmhughes** [comment]
What OS are you using?

**Comment by tambry** [comment]
I'm on Windows 10 1803 17134.81 64-bit. Physically located in Estonia, connecting to YouTube over IPv6.

1.1.5 indeed hides the errors, but the extension doesn't fulfill its purpose.

**Comment by craigmhughes** [comment]
I think I may have found the issue you're referring to. I've updated again.

**Comment by tambry** [comment]
I can confirm it works now. Thanks!
